version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: parcial-software
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www

  webserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginix
    image: nginx
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
      
  db:
    image: mysql:5.7.22
    container_name: db
    environment:
      MYSQL_DATABASE: parcial
      MYSQL_ROOT_PASSWORD: r00tadmin
    ports:
      - "3607:3606"
    volumes:
      - dbdata:/var/lib/mysql
  volumes:
    dbdata:
      drive: local