version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: parcial-software
    container_name: app
    restart: unless-stopped
    volumes:
      - ./:/var/www

  webserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginix
    image: nginx
    container_name: webserver
    restart: unless_stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./config/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app